BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX

XXXXXXX
  XXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXX XXXXXXXX
  X
XXXXXXXX
BBBBBBBB
 BBBBB BBBBB  gettext(u'Armamento')  BBBBBBBB 
 BBBBB BBBBBBB 
 XXXXXXXXXX
 BB BBBBBBBB
  XXX XXXXXXXXXXXXXXXXX
    BBB BBBBBBB BB BBBBBBBB
      XXXBB BBBBBBBBBBBB XXXXXXXXBBBBBXXXXXX
    BBBBBB
  XXXXX
BBBBB
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'ARMAMENTO') XXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Agregar nuevo armamento') 
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Crear manualmente') XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Desde un archivo excel') XXXXXXXXX
        XXXXX
    XXXXXX
    
  
      XXXX XXXXXXXXXXX XXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                
            XXXXXX
            XXXX XXXXXXXXXXXX
                
            XXXXXX
            XXXX XXXXXXXXXXXX
                
            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXXX
        XXXXXX
      XXXXXXX
      XXXXXX
  XXXXXX
  
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX
          XXX XXXXXXXXXXXX gettext(u'ID ARMA') XXXXX
          XXX XXXXXXXXXXXX gettext(u'INSTITUCIÓN') XXXXX
          XXX XXXXXXXXXXXX gettext(u'DEPENDENCIA') XXXXX
          XXX XXXXXXXXXXXX gettext(u'ENTIDAD') XXXXX
          XXX XXXXXXXXXXXX gettext(u'MUNICIPIO') XXXXX
          XXX XXXXXXXXXXXX gettext(u'CLASE') XXXXX
          XXX XXXXXXXXXXXX gettext(u'CALIBRE') XXXXX
          XXX XXXXXXXXXXXX gettext(u'MARCA') XXXXX
          XXX XXXXXXXXXXXX gettext(u'MODELO') XXXXX
          XXX XXXXXXXXXXXX gettext(u'MATRICULA') XXXXX
          XXX XXXXXXXXXXXX gettext(u'ESTADO ARMA') XXXXX
          XXX XXXXXXXXXXXX gettext(u'OBSERVACIONES') XXXXX
          XXX XXXXXXXXXXXX gettext(u'ESTATUS DEL ARMA') XXXXX
          XXX XXXXXXXXXXXX gettext(u'CUIP PORTADOR') XXXXX
          XXX XXXXXXXXXXXX gettext(u'CUIP RESPONSABLE') XXXXX
          XXX XXXXXXXXXXXX gettext(u'ACCIONES') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBB BB BBBBB
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX
            BB BBBBBBBBBBBB
                
            BBBB
                XXXXX XXXXXX
            BBBBB
          XXXXX        
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Ver') XXXX
                XX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Editar') XXXX
                XXXXXXX XXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXX gettext(u'Eliminar') XXXXXXXXX
            XXXXXX
        XXXXX
        XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXX
    BB BBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
            
        XXXXXX
    BBBBB 
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXXXXX
XXXXXX
XXXXXX
XXXX
XXXX XXXXXXXXXXXXXXXXXXX
  BBBBBBB BBBBBBBBBBBBBBBB
XXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB
