BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX
BBBBBBBB
 BBBBB BBBBB  gettext(u'Crear Armamento')  BBBBBBBB 

BBBBB BBBBBBB
XXXXXXXX
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Crear Armamento') 
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Armamento desde un archivo Excel') XXXXX
            XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Seleccione un archivo Excel') XXXXXXXX
                    XXXXXX XXXXXXX 
                    XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                    XXXXXXXXXX 
                    XXXXXXX  
                    XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Volver a Armamento') XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Descargar plantilla Excel') 
                    XXXX
                    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
                    X gettext(u'Cargar archivo') XXXXXXXXX 
                XXXXXX
            XXXXXXX
            XXXX
            BB BBBBBBBB
    XXXX XXXXXXXXXXX XXX XXXXXXXXX
        BBB BBBBBBB BB BBBBBBBB
            BB BBBBBBBBBBBB BB BBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                    
                XXXXXX
            BBBB BBBBBBBBBBBB BB BBBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    
                XXXXXX
            BBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    
                XXXXXX
            BBBBB
        BBBBBB
    XXXXXX
BBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXX
XXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB