BBBB BBBB
BBBB BBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Id del Arma') XXXXXXXXX
                XXXXXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                    XXXXXXX 
                    XXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXX gettext(u'Id del Arma') X
                    XXXXXXX FFFFFFFFFFXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Dependencia') XXXXXXXXX
                XXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Institucion') XXXXXXXXX
                XXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Entidad') XXXXXXXXX
                XXXXXXXX
            XXXXXX
  
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Municipio') XXXXXXXXX
                XXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Numero Loc:') XXXXXXXX
                XXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Folio C') XXXXXXXXX
                XXXXXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                    XXXXXXX 
                    XXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXX gettext(u'Folio C') X
                    XXXXXXX FFFFFFFFFFX
                    XXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Folio D') XXXXXXXXX
                XXXXXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                    XXXXXXX 
                    XXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXX gettext(u'Folio D') X
                    XXXXXXX FFFFFFFFFFX
                    XXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Clase del Arma') XXXXXXXXX
                XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Calibre del Arma') XXXXXXXXX
                XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Marca del Arma') XXXXXXXXX
                XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Modelo del Arma') XXXXXXXXX
                XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Matricula') XXXXXXXXX
              XXXXXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                    XXXXXXX 
                    XXXXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXX gettext(u'Matricula') X
                    XXXXXXX FFFFFFFFFFX
                    XXXXXXXX
                XXXXX
          XXXXXX
          
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Matricula Canon') XXXXXXXXX
              XXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                XXXXXXX 
                XXXXXXXXXXXXXXXXXXXXXXX 
                XXXXXXXXXXXXX gettext(u'Matricula Canon') X
                XXXXXXX FFFFFFFFFFXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Fecha') XXXXXXXXX
                XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Fecha Loc') XXXXXXXXX
                XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX  gettext(u'Estado del Arma') XXXXXXXXX
                XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Fecha de Captura') XXXXXXXXX
                XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Observaciones') XXXXXXXXX
              XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Estatus del Arma') XXXXXXXXX
              XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'CUIP Portador') XXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                XXXXXXX 
                XXXXXXXXXXXXXXXXXXXXX 
                XXXXXXXXXXXXX gettext(u'CUIP Portador') X
                XXXXXXX FFFFFFFFFFX
                XXXXXXXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'CUIP Responsable') XXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                XXXXXXX 
                XXXXXXXXXXXXXXXXXXXXXXXX 
                XXXXXXXXXXXXX gettext(u'CUIP Responsable') X
                XXXXXXX FFFFFFFFFFX
                XXXXXXXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                XXXXXXX 
                XXXXXXXXXXXX 
                XXXXXXXXXXXXXX
                XXXXXXX FFFFFFFFFFXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Tipo de Funcionamiento') XXXXXXXXX
                XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Tipo de Propiedad') XXXXXXXXX
                XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Fecha de Baja Logica') XXXXXXXXX
              XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Motivo de baja') XXXXXXXXX
              XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Documento de Baja') XXXXXXXXX
              XXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                XXXXXXX 
                XXXXXXXXXXXXXXXXXXXXXX 
                XXXXXXXXXXXXX gettext(u'Documento de Baja') X
                XXXXXXX FFFFFFFFFFXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Observaciones de Baja') XXXXXXXXX
              XXXXXXXX
            XXXXXX
        
            XXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Fecha de baja del documento') XXXXXXXXX
              XXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX   

              

    BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX
                BBB BBBBB BB BBBB
                    BBB BBBBB BB BBBBBBBBBBBB
                        XXXXXXXXX
                    BBBBBB
                BBBBBB
            XXXXX
        XXXXXX
    BBBBB

    XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Guardar') XX XXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Volver') XXXX
XXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

BB BBBBBBBBBB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBB
