    BBBB BBBB
    XXXX XXXXXX XXX
    XXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
            X
      XXXX XXXX XXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXX XXX XXXXXX
        XXXX XXXXXXXX XXXXX XXX
        XXXXXXXXX
          XXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX
              XXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXX XXXXXX XXX
            XXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XX
  
            XXXX XXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'CONTACTO') XXXXX
              XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Teodoro Gamero 165, Sentimientos de la Nación, 58178 Morelia, Mich.') XXXX
              XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXX XXX XXXXXXXXXXX
            XXXXXX
            XXXX XXXX XXXXXX XXX
            
            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Siguenos!') XXXXX
  
              XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXX XX XXXXXXXX XXX
                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                  XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX
              
                XXXX XXXXX XX XXXXXXX XXX
                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                  XX XXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX
              XXXXXX
              
            XXXXXX
          XXXXXX
          XXXXXXXX XXXXXX
        XXXXXXXXXX
        XXXX XXXXXXXX XXXXX XXX
      XXXXXX
      XXXX XXXX XXXXXXXXX XXX
  
      XXXX XXXXXXXXX XXX
      XXXX
           XXXXXXXXXXXXXXXXXX XXXX
           XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XX XXXXX
           X
         gettext(u'© 2024 Copyright') 
      XXXXXX
      XXXX XXXXXXXXX XXX
    XXXXXXXXX
    XXXX XXXXXX XXX
