BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX
BBBBBBBB
 BBBBB BBBBB  gettext(u'Inicio')  BBBBBBBB 
BBBBB BBBBBBB
XXXX
XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX 
  XXXXXX
  X
  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXXXXXXX XXXXXX XXXX
  XXXXXXX XXXXXX
  XXXXXXXXXX XXXXXX
  XXXXXXX X XXXXX
  XX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XX XXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXX gettext(u'Bienvenido ') XXXXX
    XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX gettext(u'Armamento') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX gettext(u'Imagenes') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB  BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX gettext(u'Catalogos') XXXX
      XXXXXX
    XXXXXX
  XXXXXX
  
  
XXXXXX
BBBBBBBB
