BBBB BBBB
BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBB BBBBBBBB
    XXXXXXXBBBBB BBBBB BBBBBBBBXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
  XXXXXXX
  XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBXX gettext(u'Home') XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Armamento') XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Imágenes') XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Catalogos') XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX
              XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Lenguaje') 
              XXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBXX gettext(u'Español') 
                XXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBXX gettext(u'Ingles') 
                XXXXXXXXX
              XXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX gettext(u'Cerrar Sesión') XXXX
            XXXXX
            
            BBBB
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Registrarse') XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Iniciar Sesión') XXXX
            XXXXX
            BBBBB
          XXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      BBBBB BBBBBBB 
      BBBBBBBB
    XXXXXX
  XXXXXXX
  BBBBBBB BBBBBBBBBBBBB
XXXXXXX
