BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX BBBBBBBB
 BBBBB BBBBB  gettext(u'Iniciar sesión') BBBBBBBB 

BBBBB BBBBBBB
XXXX XXXXXXXX XXXXXX XXXXX XXX
XXXXXXXX

XXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXX
              XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX X XXXX XXXX XXX XX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX

                XXXXX XXXXXXXXX XXXXXXXXXXXXXX
                  BBBBBBBBBB
                  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX
                      XXXXX XXXXXXXXX XXXXXXX XXXXXXXXX gettext(u'Bienvenido!') XXXXXXX
                  XXXXXX
                  
                  XXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Inicia sesión con tu perfil') XXXXX
              
                  XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Usuario') XXXXXXXX
                  XXXXXX
              
                  XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Contraseña') XXXXXXXX
                  XXXXXX
              
                  XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                      
                  XXXXXX
              
                  XXXX XXXXXXXXXXX XXXXXX
                      XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX gettext(u'Ingresar') XXXXXXXXX
                  XXXXXX
              
                  XXXX XXXXXXX XXXXXXX XX XXXXX XXXXXXXXXX XXX XXXXXXX XXX
                  BB BBBBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
                      
                  XXXXXX
              BBBBB
          
              XXXX XXXXXXX XXXXXXX XX XXXXX XXXXXXX XXX
              BB BBBBB BBB BBB BBBBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
                      
                  XXXXXX
              BBBBB
              XXXXXXX
              
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX


  XXXX XXXXXXXX XXXXXX XXXXX XXX
BBBBBBBB