BBBBBBB BBBBBBBBBBBBB 
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB
BBBBB BBBBB  gettext(u'Dependencias')  BBBBBBBB 

BBBBB BBBBBBB 
XXX XXXXX XX
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'DEPENDENCIAS') XXXXX
    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Volver a Catalogos') XXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'TIPO DE DEPENDENCIA') XXXXX
          XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'ID DEPENDENCIAS') XXXXX
          XXX XXXXXXXXXXXX gettext(u'DEPENDENCIA') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBBBBBBBBB BB BBBBBBBBBBBB
        XXX XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXX
BBBBBBBB