BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB
BBBBB BBBBB  gettext(u'Estados de conservacion')  BBBBBBBB 

BBBBB BBBBBBB

XXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'ESTADO DE CONSERVACIÓN') XXXXX
    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Volver a Catalogos') XXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXX gettext(u'ID ESTADO') XXXXX
                XXX XXXXXXXXXXXX gettext(u'DESCRIPCIÓN') XXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBBBB BB BBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXX
XXXXXX

BBBBBBBB