BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB
 BBBBB BBBBB  gettext(u'Estatus de armas')  BBBBBBBB 

BBBBB BBBBBBB

XXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'ESTATUS DE LAS ARMAS') XXXXX
    XX XXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Volver a Catalogos') XXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXX gettext(u'ESTATUS') XXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBBBB BB BBBBBBB
            XXX XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXXX
XXXXXX

BBBBBBBB