BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB
 BBBBB BBBBB  gettext(u'Marcas')  BBBBBBBB 

BBBBB BBBBBBB
XXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'MARCAS') XXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Volver a Catalogos') XXXX
        XXXX XXXXXXXXXXX XXXXXXXXX
          XXXXX XXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXX
                  
              XXXXXX
              XXXX XXXXXXXXXXXX
                  
              XXXXXX
              XXXX XXXXXXXXXXXX
                  
              XXXXXX
              XXXX XXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXXXXXX
                  XXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXX
                  XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXX
              XXXXXX
          XXXXXX
          XXXXXXX
        XXXXXX
      XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXX gettext(u'MARCA') XXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBBB BB BBBBB
            XXX XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX
  XXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXX XXXXXX
  BB BBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
          
      XXXXXX
  BBBBB
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBB
XXXXXX

BBBBBBBB