BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB
 BBBBB BBBBB  gettext(u'Municipios')  BBBBBBBB 

BBBBB BBBBBBB
XXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'MUNICIPIOS') XXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Volver a Catalogos') XXXX
        XXXXX
          XXXXX XXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXX
                  
              XXXXXX
              XXXX XXXXXXXXXXXX
                  
              XXXXXX
              XXXX XXXXXXXXXXXX
                  
              XXXXXX
              XXXX XXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXXXXXX
                  XXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXX
                  XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBX XXXXXXXXXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXX
              XXXXXX
          XXXXXX
          XXXXXXX
        XXXXXX
      XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX
                XXX XXXXXXXXXXXX gettext(u'ENTIDAD') XXXXX
                XXX XXXXXXXXXXXX gettext(u'ID MUNICIPIO') XXXXX
                XXX XXXXXXXXXXXX gettext(u'MUNICIPIO') XXXXX
            XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
            BBB BBBBBBBBB BB BBBBB
            XXX XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXX XXXXXX
  BB BBBBBBB
      XXXX XXXXXXX XX XXXXXXX XX XXXXXXXXX XX XXXX XXXXXXXX XXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
          
      XXXXXX
  BBBBB
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
  BBBBBBB BBBBBBBBBBBBBBBB
XXXXXX
BBBBBBBB