BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB
 BBBBB BBBBB  gettext(u'Tipos de alta')  BBBBBBBB 

BBBBB BBBBBBB
XXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'TIPOS DE ALTA') XXXXX
    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Volver a Catalogos') XXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXX gettext(u'TIPO') XXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBB BB BBBBB
            XXX XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXXX
XXXXXX

BBBBBBBB