# Generated by Django 3.2.21 on 2024-01-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='ID_MARCA',
            new_name='ID_MARCAS',
        ),
    ]
