# Generated by Django 4.2.3 on 2023-07-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_municipio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('ID_MUNICIPIO', 'ID_ENTIDAD')},
        ),
    ]
