# Generated by Django 4.2.3 on 2023-07-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_municipio_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together=set(),
        ),
    ]
