# Generated by Django 4.2.3 on 2023-07-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_alter_municipio_id_entidad'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('ID_ENTIDAD', 'ID_MUNICIPIO')},
        ),
    ]
