# Generated by Django 4.2.3 on 2023-07-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_municipio_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
