# Generated by Django 4.2.3 on 2023-07-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_municipio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
