# Generated by Django 4.2.3 on 2023-07-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('ID_ALTERNA', models.AutoField(primary_key=True, serialize=False)),
                ('ID_ARMA', models.DecimalField(decimal_places=0, max_digits=10)),
                ('FOLIO_C', models.CharField(max_length=20)),
                ('FOLIO_D', models.CharField(max_length=20)),
                ('MATRICULA', models.CharField(max_length=20)),
                ('MATRICULA_CANON', models.CharField(blank=True, max_length=40)),
                ('FECHA', models.DateField()),
                ('FECHA_LOC', models.DateField()),
                ('FECHA_CAPTURA', models.DateField()),
                ('OBSERVACIONES', models.TextField()),
                ('CUIP_PORTADOR', models.CharField(max_length=20)),
                ('CUIP_RESPONSABLE', models.CharField(max_length=20)),
                ('CIHB', models.CharField(max_length=20)),
                ('FECHA_BAJA_LOGICA', models.DateField()),
                ('MOTIVO_BAJA', models.TextField()),
                ('DOCUMENTO_BAJA', models.CharField(max_length=20)),
                ('OBSERVACIONES_BAJA', models.TextField()),
                ('FECHA_BAJA_DOCUMENTO', models.DateField()),
                ('CALIBRE_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.calibre')),
                ('CLASE_TIPO_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.tipo')),
                ('DEPENDENCIA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.dependencia')),
                ('ENTIDAD', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.entidad')),
                ('ESTADO_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.edo_conservacion')),
                ('ESTATUS_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.estatus_arma')),
                ('INSTITUCION', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.institucion')),
                ('MARCA_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.marca')),
                ('MODELO_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.modelo')),
                ('NUMERO_LOC', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.loc')),
            ],
        ),
    ]
