# Generated by Django 4.2.3 on 2023-07-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_armamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
