# Generated by Django 4.2.3 on 2023-07-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_delete_municipio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Armamento',
        ),
    ]
