# Generated by Django 4.2.3 on 2023-07-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_delete_armamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_MUNICIPIO', models.DecimalField(decimal_places=0, max_digits=10)),
                ('MUNICIPIO', models.CharField(max_length=70)),
                ('ID_ENTIDAD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.dependencia')),
            ],
            options={
                'unique_together': {('ID_ENTIDAD', 'ID_MUNICIPIO')},
            },
        ),
    ]
