# Generated by Django 4.2.3 on 2023-07-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0015_armamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='ID_ENTIDAD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.entidad'),
        ),
    ]
