# Generated by Django 4.2.3 on 2023-07-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_alter_municipio_id_entidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Armamento',
        ),
    ]
