# Generated by Django 3.2.21 on 2023-11-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_delete_armamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFuncinamiento',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TipoFuncionamiento', models.TextField(max_length=20)),
                ('Status', models.IntegerField(choices=[(0, 'Deshabilitado'), (1, 'Habilitado')])),
            ],
        ),
    ]
