# Generated by Django 3.2.21 on 2023-11-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0018_tipofuncinamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Propiedad', models.TextField(max_length=20)),
                ('Status', models.IntegerField(choices=[(0, 'Deshabilitado'), (1, 'Habilitado')])),
            ],
        ),
    ]
