BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB
 BBBBB BBBBB  gettext(u'Editar Imagen')  BBBBBBBB 

BBBBB BBBBBBB
XXXXXXXX
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Editar Imagen') 
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u'Datos de la Imagen') XXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBB
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXX
XXXXXX

BBBBBBBB