BBBB BBBB
BBBB BBBBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB
XXXX
  XXXX XXXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Matricula del Arma existente') XXXXXXXXX
      
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Dependencia') XXXXXXXXX
        XXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Institución') XXXXXXXXX
      XXXXXXXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXX XXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Entidad Federativa') XXXXXXXXX
      XXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXFFFFFXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXFFFFFX XXXXXXX FFFFFFFFFFX XXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

  XXXXXX

  XXXX XXXXXXXXXXX XXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXFFFFFXXXXXXXXX
      XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXFFFFFX XXXXXXX FFFFFFFFFFX XXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Tipo de Imagen') XXXXXXXXX
      XXXXXXXXXXX
    XXXXXX

  XXXXXX

  XXXX XXXXXXXXXXX XXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXFFFFFXXXXXXXXX
      XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXFFFFFX XXXXXXX FFFFFFFFFFX XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Grupo') XXXXXXXXX
      XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXFFFFFX XXXXXXX FFFFFFFFFFX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

  XXXXXX

XXXX XXXXXXXXXXX XXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Imagen del Arma') XXXXXXXXX
    BB BBBBBBBBBBBBBBBBB
      XXXX
      XXXX XXXXXX XXXXXXXXXXXX
      XXXX
    BBBBB
    
  XXXXXX
XXXXXX

  BB BBBBBBBB
    XXX XXXXXXXXXXXXXXXXX
      BBB BBBBBBB BB BBBBBBBB
        XXXBB BBBBBBBBBBBB XXXXXXXXBBBBBXXXXXX
      BBBBBB
    XXXXX
  BBBBB

  XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Guardar') XX XXXXXXXXXXXXXXXXX
  XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Volver') XXXX
XXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BB BBBBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBB
