BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB
 BBBBB BBBBB  gettext(u'Imagenes')  BBBBBBBB 

BBBBB BBBBBBB
XXXXXXXX
BB BBBBBBBB
  XXX XXXXXXXXXXXXXXXXX
    BBB BBBBBBB BB BBBBBBBB
      XXXBB BBBBBBBBBBBB XXXXXXXXBBBBBXXXXXX
    BBBBBB
  XXXXX
BBBBB
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'IMÁGENES') XXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
               gettext(u'Agregar nueva imagen') 
          XXXX
      
          XXXX XXXXXXXXXXX XXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXX
                      
                  XXXXXX
                  XXXX XXXXXXXXXXXX
                      
                  XXXXXX
                  XXXX XXXXXXXXXXXX
                      
                  XXXXXX
                  XXXX XXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                          XX XXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXX
                      XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXXX
                          XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                      XXXX
                  XXXXXX
              XXXXXX
              XXXXXXX
          XXXXXX
      XXXXXX
      
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXX gettext(u'ID ARMA') XXXXX
                XXX XXXXXXXXXXXX gettext(u'IMAGEN') XXXXX
                XXX XXXXXXXXXXXX gettext(u'DEPENDENCIA') XXXXX
                XXX XXXXXXXXXXXX gettext(u'INSTITUCIÓN') XXXXX
                XXX XXXXXXXXXXXX gettext(u'ENTIDAD') XXXXX
                XXX XXXXXXXXXXXX gettext(u'IMAKEY') XXXXX
                XXX XXXXXXXXXXXX gettext(u'DESIMA') XXXXX
                XXX XXXXXXXXXXXX gettext(u'TIPO') XXXXX
                XXX XXXXXXXXXXXX gettext(u'FOLIO') XXXXX
                XXX XXXXXXXXXXXX gettext(u'GRUPO') XXXXX
                XXX XXXXXXXXXXXX gettext(u'ACCIONES') XXXXX
              XXXXX
            XXXXXXXX
            XXXXXXX
              BBB BBBBBB BB BBBBB
              XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXX
                XXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXX XXXXXXXXXXXX XXXXXXX
                  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXX  XXXXX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX gettext(u'Editar') XXXX
                    XXXXXXX XXXXXXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX  XXXXXX gettext(u'Eliminar') XXXXXXXXX
                  XXXXXX
                XXXXX
              XXXXX
              BBBBBB
            XXXXXXXX
          XXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXX
      BB BBBBBBB
          XXXX XXXXXXX XX XXXXXXX XX XXXXXXXXX XX XXXX XXXXXXXX XXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
              
          XXXXXX
      BBBBB
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXX
XXXXXX
XXXXXX
XXXX
XXXX XXXXXXXXXXXXXXXXXXX
  BBBBBBB BBBBBBBBBBBBBBBB
XXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB
