# Generated by Django 4.2.3 on 2023-07-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portadores',
            fields=[
                ('CUIB', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=30)),
                ('APELLIDO_PATERNO', models.CharField(max_length=30)),
                ('APELLIDO_MATERNO', models.CharField(max_length=30)),
                ('CORREO', models.EmailField(max_length=254, unique=True)),
                ('TELEFONO', models.CharField(max_length=10)),
                ('IMAGEN', models.ImageField(null=True, upload_to='imagenes/')),
            ],
        ),
    ]
