# Generated by Django 4.2.3 on 2023-07-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portadores',
            name='IMAGEN',
            field=models.ImageField(null=True, upload_to='portadores/imagenes/'),
        ),
    ]
