# Generated by Django 4.2.3 on 2023-07-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0002_alter_portadores_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portadores',
            new_name='Portador',
        ),
    ]
