# Generated by Django 4.2.3 on 2023-07-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0003_rename_portadores_portador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portador',
            old_name='CUIB',
            new_name='CUIP',
        ),
    ]
