# Generated by Django 4.2.3 on 2023-07-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0004_rename_cuib_portador_cuip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portador',
            name='IMAGEN',
            field=models.ImageField(upload_to='portadores/imagenes/'),
        ),
    ]
