# Generated by Django 4.2.3 on 2023-07-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0007_alter_portador_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portador',
            name='CORREO',
            field=models.EmailField(max_length=254),
        ),
    ]
