# Generated by Django 4.2.3 on 2023-08-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0013_alter_portador_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portador',
            name='IMAGEN',
            field=models.FileField(upload_to='images/portadores/'),
        ),
    ]
