# Generated by Django 4.2.3 on 2023-08-30 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portadores', '0014_alter_portador_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPortador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('CUIP', models.CharField(max_length=20)),
                ('NOMBRE', models.CharField(max_length=30)),
                ('APELLIDO_PATERNO', models.CharField(max_length=30)),
                ('APELLIDO_MATERNO', models.CharField(max_length=30)),
                ('CORREO', models.EmailField(max_length=254)),
                ('TELEFONO', models.CharField(max_length=10)),
                ('IMAGEN', models.FileField(upload_to='images/portadores/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
