# Generated by Django 4.2.3 on 2023-08-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0015_logportador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogPortador',
        ),
    ]
