# Generated by Django 4.2.3 on 2023-08-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0016_delete_logportador'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPortador',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('CUIP', models.CharField(max_length=20)),
                ('NOMBRE', models.CharField(max_length=30)),
                ('APELLIDO_PATERNO', models.CharField(max_length=30)),
                ('APELLIDO_MATERNO', models.CharField(max_length=30)),
                ('CORREO', models.EmailField(max_length=254)),
                ('TELEFONO', models.CharField(max_length=10)),
                ('IMAGEN', models.FileField(upload_to='images/portadores/')),
            ],
        ),
    ]
