# Generated by Django 4.2.3 on 2023-08-31 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0017_logportador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogPortador',
        ),
    ]
