# Generated by Django 4.2.3 on 2023-08-31 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0018_delete_logportador'),
    ]

    operations = [
        migrations.AddField(
            model_name='portador',
            name='ultima_modificacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
