# Generated by Django 4.2.3 on 2023-08-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0020_portador_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portador',
            name='usuario',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
