# Generated by Django 4.2.3 on 2023-08-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0022_alter_portador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portador',
            name='usuario',
        ),
    ]
