# Generated by Django 4.2.3 on 2023-08-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0025_alter_portador_ultima_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portador',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
