# Generated by Django 4.2.3 on 2023-09-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0027_alter_portador_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortadorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_portador', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=50)),
                ('ultima_modificacion', models.DateTimeField()),
            ],
        ),
    ]
