# Generated by Django 4.2.3 on 2023-09-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0028_portadorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portadorlog',
            name='id_portador',
            field=models.CharField(max_length=20),
        ),
    ]
