# Generated by Django 4.2.3 on 2023-09-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0029_alter_portadorlog_id_portador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portador',
            name='IMAGEN',
            field=models.FileField(upload_to='portadores/'),
        ),
    ]
