# Generated by Django 4.2.3 on 2023-09-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0031_alter_portador_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortadorLog',
        ),
    ]
