# Generated by Django 4.2.3 on 2023-09-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0032_delete_portadorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortadorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_portador', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('imagen', models.FileField(upload_to='respaldo/portadores/')),
                ('usuario', models.CharField(max_length=50)),
                ('ultima_modificacion', models.DateTimeField()),
            ],
        ),
    ]
