# Generated by Django 4.2.3 on 2023-09-14 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portadores', '0034_alter_portador_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portador',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
