# Generated by Django 3.2.21 on 2023-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0036_alter_portador_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portador',
            name='CORREO',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='portador',
            name='IMAGEN',
            field=models.FileField(unique=True, upload_to='images/portadores/'),
        ),
        migrations.AlterField(
            model_name='portador',
            name='TELEFONO',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
