# Generated by Django 3.2.21 on 2023-11-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0037_auto_20230925_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portador',
            name='IMAGEN',
            field=models.ImageField(unique=True, upload_to='images/portadores/'),
        ),
        migrations.AlterField(
            model_name='portadorlog',
            name='imagen',
            field=models.ImageField(upload_to='respaldo/portadores/'),
        ),
    ]
