# Generated by Django 3.2.21 on 2023-11-28 19:37

import armamento.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmamentoLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('id_alterna', models.DecimalField(decimal_places=0, max_digits=10)),
                ('id_arma', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('institucion', models.CharField(max_length=70)),
                ('dependencia', models.CharField(max_length=70)),
                ('entidad', models.CharField(max_length=70)),
                ('municipio', models.CharField(max_length=70)),
                ('numero_loc', models.CharField(max_length=20)),
                ('folio_c', models.CharField(max_length=20)),
                ('folio_d', models.CharField(max_length=20)),
                ('clase_tipo_arma', models.CharField(max_length=50)),
                ('calibre_arma', models.CharField(max_length=50)),
                ('marca_arma', models.CharField(max_length=50)),
                ('modelo_arma', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=20)),
                ('matricula_canon', models.CharField(max_length=40, null=True)),
                ('fecha', models.DateField()),
                ('fecha_loc', models.DateField()),
                ('estado_arma', models.CharField(max_length=20, null=True)),
                ('fecha_captura', models.DateField()),
                ('observaciones', models.TextField()),
                ('estatus_arma', models.CharField(max_length=30)),
                ('cuip_portador', models.CharField(max_length=20)),
                ('cuip_responsable', models.CharField(max_length=20)),
                ('tipo_funcionamiento', models.CharField(default='OTRO', max_length=20)),
                ('propiedad', models.CharField(default='OTRO', max_length=20)),
                ('cihb', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_baja_logica', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.TextField(blank=True, null=True)),
                ('documento_baja', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones_baja', models.TextField(blank=True, null=True)),
                ('fecha_baja_documento', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(max_length=50)),
                ('ultima_modificacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('ID_ALTERNA', models.AutoField(primary_key=True, serialize=False)),
                ('ID_ARMA', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('FOLIO_C', models.CharField(max_length=20)),
                ('FOLIO_D', models.CharField(max_length=20)),
                ('MATRICULA', models.CharField(max_length=20, unique=True)),
                ('MATRICULA_CANON', models.CharField(blank=True, max_length=40, null=True)),
                ('FECHA', models.DateField(validators=[armamento.models.validate_fecha_no_anterior_1990])),
                ('FECHA_LOC', models.DateField(validators=[armamento.models.validate_fecha_no_anterior_1990])),
                ('FECHA_CAPTURA', models.DateField(validators=[armamento.models.validate_fecha_no_anterior_1990])),
                ('OBSERVACIONES', models.TextField()),
                ('CUIP_PORTADOR', models.TextField(validators=[armamento.models.validate_cuip_formato])),
                ('CUIP_RESPONSABLE', models.TextField(validators=[armamento.models.validate_cuip_formato])),
                ('CIHB', models.CharField(blank=True, max_length=20, null=True)),
                ('FECHA_BAJA_LOGICA', models.DateField(blank=True, null=True, validators=[armamento.models.validate_fecha_no_anterior_1990])),
                ('MOTIVO_BAJA', models.TextField(blank=True, null=True)),
                ('DOCUMENTO_BAJA', models.CharField(blank=True, max_length=20, null=True)),
                ('OBSERVACIONES_BAJA', models.TextField(blank=True, null=True)),
                ('FECHA_BAJA_DOCUMENTO', models.DateField(blank=True, null=True, validators=[armamento.models.validate_fecha_no_anterior_1990])),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('CALIBRE_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.calibre')),
                ('CLASE_TIPO_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.tipo')),
                ('DEPENDENCIA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.dependencia')),
                ('ENTIDAD', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.entidad')),
                ('ESTADO_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.edo_conservacion')),
                ('ESTATUS_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.estatus_arma')),
                ('INSTITUCION', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.institucion')),
                ('MARCA_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.marca')),
                ('MODELO_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.modelo')),
                ('MUNICIPIO', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.municipio')),
                ('NUMERO_LOC', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.loc')),
                ('PROPIEDAD', models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.propiedad')),
                ('TIPO_FUNCIONAMIENTO', models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.tipofuncinamiento')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
