# Generated by Django 4.2.3 on 2023-07-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='ID_ARMA',
            field=models.DecimalField(decimal_places=0, max_digits=10, unique=True),
        ),
    ]
