# Generated by Django 4.2.3 on 2023-08-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0002_alter_armamento_id_arma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='CIHB',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='DOCUMENTO_BAJA',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='FECHA_BAJA_DOCUMENTO',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='FECHA_BAJA_LOGICA',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='MATRICULA_CANON',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='MOTIVO_BAJA',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='OBSERVACIONES_BAJA',
            field=models.TextField(blank=True, null=True),
        ),
    ]
