# Generated by Django 4.2.3 on 2023-08-14 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0012_alter_portador_imagen'),
        ('armamento', '0003_alter_armamento_cihb_alter_armamento_documento_baja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armamento',
            name='CUIP_RESPONSABLE',
        ),
        migrations.AlterField(
            model_name='armamento',
            name='CUIP_PORTADOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='armamento_portador', to='portadores.portador'),
        ),
    ]
