# Generated by Django 4.2.3 on 2023-08-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portadores', '0012_alter_portador_imagen'),
        ('armamento', '0004_remove_armamento_cuip_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armamento',
            name='CUIP_RESPONSABLE',
            field=models.ForeignKey(default='nadie', on_delete=django.db.models.deletion.RESTRICT, related_name='armamento_responsable', to='portadores.portador'),
        ),
    ]
