# Generated by Django 4.2.3 on 2023-09-08 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('armamento', '0007_alter_armamento_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmamentoLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('id_arma', models.DecimalField(decimal_places=0, max_digits=10)),
                ('institucion', models.CharField(max_length=70)),
                ('dependencia', models.CharField(max_length=70)),
                ('entidad', models.CharField(max_length=70)),
                ('municipio', models.CharField(max_length=70)),
                ('numero_loc', models.CharField(max_length=20)),
                ('folio_c', models.CharField(max_length=20)),
                ('folio_d', models.CharField(max_length=20)),
                ('clase_tipo_arma', models.CharField(max_length=50)),
                ('calibre_arma', models.CharField(max_length=50)),
                ('marca_arma', models.CharField(max_length=50)),
                ('modelo_arma', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=20)),
                ('matricula_canon', models.CharField(max_length=40, null=True)),
                ('fecha', models.DateField()),
                ('fecha_loc', models.DateField()),
                ('estado_arma', models.CharField(max_length=20, null=True)),
                ('fecha_captura', models.DateField()),
                ('observaciones', models.TextField()),
                ('estatus_arma', models.CharField(max_length=30, null=True)),
                ('cuip_portador', models.CharField(max_length=20, null=True)),
                ('cuip_responsable', models.CharField(max_length=20, null=True)),
                ('cihb', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo_baja', models.TextField(blank=True, null=True)),
                ('documento_baja', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones_baja', models.TextField(blank=True, null=True)),
                ('fecha_baja_logica', models.DateField(blank=True, null=True)),
                ('ultima_modificacion', models.DateTimeField()),
                ('id_alterna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='armamento.armamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
