# Generated by Django 4.2.3 on 2023-09-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0008_armamentolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='armamentolog',
            name='fecha_baja_documento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
