# Generated by Django 4.2.3 on 2023-09-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0009_armamentolog_fecha_baja_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamentolog',
            name='cihb',
            field=models.CharField(default='x', max_length=20),
        ),
        migrations.AlterField(
            model_name='armamentolog',
            name='cuip_portador',
            field=models.CharField(default='nadie', max_length=20),
        ),
        migrations.AlterField(
            model_name='armamentolog',
            name='cuip_responsable',
            field=models.CharField(default='nadie', max_length=20),
        ),
        migrations.AlterField(
            model_name='armamentolog',
            name='estado_arma',
            field=models.CharField(default='nadie', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='armamentolog',
            name='estatus_arma',
            field=models.CharField(default='nadie', max_length=30),
        ),
    ]
