# Generated by Django 4.2.3 on 2023-09-08 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0011_alter_armamentolog_cihb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armamento',
            old_name='ultima_modificacion',
            new_name='x',
        ),
    ]
