# Generated by Django 4.2.3 on 2023-09-12 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0013_rename_x_armamento_ultima_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamentolog',
            name='id_alterna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='armamento.armamento'),
        ),
    ]
