# Generated by Django 4.2.3 on 2023-09-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0017_alter_armamentolog_id_alterna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
    ]
