# Generated by Django 3.2.21 on 2023-10-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0021_auto_20231027_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='ID_ARMA',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='MATRICULA',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
