# Generated by Django 3.2.21 on 2023-11-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0023_alter_armamentolog_cihb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamentolog',
            name='id_arma',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
