# Generated by Django 3.2.21 on 2023-11-08 22:29

import armamento.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0018_tipofuncinamiento'),
        ('armamento', '0024_alter_armamentolog_id_arma'),
    ]

    operations = [
        migrations.AddField(
            model_name='armamento',
            name='TIPO_FUNCIONAMIENTO',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.tipofuncinamiento'),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='FECHA',
            field=models.DateField(validators=[armamento.models.validate_fecha_no_anterior_1990]),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='FECHA_BAJA_DOCUMENTO',
            field=models.DateField(blank=True, null=True, validators=[armamento.models.validate_fecha_no_anterior_1990]),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='FECHA_BAJA_LOGICA',
            field=models.DateField(blank=True, null=True, validators=[armamento.models.validate_fecha_no_anterior_1990]),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='FECHA_CAPTURA',
            field=models.DateField(validators=[armamento.models.validate_fecha_no_anterior_1990]),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='FECHA_LOC',
            field=models.DateField(validators=[armamento.models.validate_fecha_no_anterior_1990]),
        ),
    ]
