# Generated by Django 3.2.21 on 2023-11-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0025_auto_20231108_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='armamentolog',
            name='tipo_funcionamiento',
            field=models.CharField(default='OTRO', max_length=20),
        ),
    ]
