# Generated by Django 3.2.21 on 2023-11-24 17:36

import armamento.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0019_propiedad'),
        ('armamento', '0026_armamentolog_tipo_funcionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='armamento',
            name='PROPIEDAD',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.propiedad'),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='CUIP_PORTADOR',
            field=models.TextField(validators=[armamento.models.validate_cuip_formato]),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='CUIP_RESPONSABLE',
            field=models.TextField(validators=[armamento.models.validate_cuip_formato]),
        ),
    ]
