# Generated by Django 3.2.21 on 2023-11-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0027_auto_20231124_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='armamentolog',
            name='propiedad',
            field=models.CharField(default='OTRO', max_length=20),
        ),
    ]
