BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
BBBBBBBB
 BBBBB BBBBB  gettext(u'Portadores')  BBBBBBBB 
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX 
    XXXXXXXXX XXXXXXXX
    XXXXXXXXX XXXX XXXXX XXXX XXXX XXXXXX XX XXXXXXXXXX
    XX XXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX 
BBBBBBBB
