BBBB BBBB
    XXXXX XXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Primera') XXXX
        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Anterior') XXXX
    BBBBB

    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    BB BBBBBBBBBBBBBB
        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Siguiente') XXXX

        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'última')  XXXXXXXXXXX
    BBBBB
    XXXXXXX
