# Generated by Django 3.2.21 on 2024-07-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
