# Generated by Django 3.2.21 on 2024-07-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personas',
        ),
    ]
