# Generated by Django 3.2.21 on 2024-07-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0003_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
