# Generated by Django 3.2.21 on 2023-11-06 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0017_delete_armamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imakey', models.DecimalField(decimal_places=0, max_digits=10)),
                ('desima', models.CharField(max_length=80)),
                ('folio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('grupo', models.CharField(max_length=1)),
                ('imagen', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('ultima_modificacion', models.DateTimeField()),
                ('institucion', models.CharField(max_length=80)),
                ('dependencia', models.CharField(max_length=80)),
                ('entidad', models.CharField(max_length=50)),
                ('id_alterna', models.DecimalField(decimal_places=0, max_digits=10)),
                ('id_arma', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('ID_ALTERNA', models.AutoField(primary_key=True, serialize=False)),
                ('ID_ARMA', models.CharField(max_length=20)),
                ('IMAKEY', models.DecimalField(decimal_places=0, max_digits=10)),
                ('DESIMA', models.CharField(max_length=80)),
                ('FOLIO', models.DecimalField(decimal_places=0, max_digits=10)),
                ('GRUPO', models.CharField(max_length=1)),
                ('IMAGEN', models.CharField(max_length=100, unique=True)),
                ('ultima_modificacion', models.DateTimeField()),
                ('DEPENDENCIA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.dependencia')),
                ('ENTIDAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.entidad')),
                ('INSTITUCION', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.institucion')),
                ('TIPO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.tipo_imagen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
