# Generated by Django 3.2.21 on 2023-11-28 19:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imakey', models.DecimalField(decimal_places=0, max_digits=10)),
                ('desima', models.CharField(max_length=80)),
                ('folio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('grupo', models.CharField(max_length=1)),
                ('imagen', models.ImageField(upload_to='respaldo/imagenes/')),
                ('usuario', models.CharField(max_length=50)),
                ('ultima_modificacion', models.DateTimeField()),
                ('institucion', models.CharField(max_length=80)),
                ('dependencia', models.CharField(max_length=80)),
                ('entidad', models.CharField(max_length=50)),
                ('id_alterna', models.DecimalField(decimal_places=0, max_digits=10)),
                ('id_arma', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('ID_ALTERNA', models.AutoField(primary_key=True, serialize=False)),
                ('IMAKEY', models.DecimalField(decimal_places=0, max_digits=10)),
                ('DESIMA', models.CharField(max_length=80)),
                ('FOLIO', models.DecimalField(decimal_places=0, max_digits=10)),
                ('GRUPO', models.CharField(max_length=1)),
                ('IMAGEN', models.ImageField(unique=True, upload_to='images/imagenes/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('DEPENDENCIA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.dependencia')),
                ('ENTIDAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.entidad')),
                ('ID_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='armamento.armamento', to_field='MATRICULA')),
                ('INSTITUCION', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.institucion')),
                ('TIPO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.tipo_imagen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
