# Generated by Django 4.2.3 on 2023-07-26 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armamento', '0002_alter_armamento_id_arma'),
        ('catalogos', '0017_delete_armamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('ID_ALTERNA', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('IMAKEY', models.DecimalField(decimal_places=0, max_digits=10)),
                ('DESIMA', models.CharField(max_length=80)),
                ('FOLIO', models.DecimalField(decimal_places=0, max_digits=10)),
                ('GRUPO', models.CharField(max_length=1)),
                ('IMAGEN', models.BinaryField()),
                ('DEPENDENCIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.dependencia')),
                ('ENTIDAD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.entidad')),
                ('ID_ARMA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armamento.armamento', to_field='ID_ARMA')),
                ('INSTITUCION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.institucion')),
                ('TIPO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipo_imagen')),
            ],
        ),
    ]
