# Generated by Django 3.2.21 on 2023-11-30 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0001_initial'),
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='DEPENDENCIA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.dependencia'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='ENTIDAD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.entidad'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='INSTITUCION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.institucion'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='TIPO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.tipo_imagen'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
