# Generated by Django 3.2.21 on 2023-11-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0024_alter_armamentolog_id_arma'),
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='ID_ARMA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='armamento.armamento', to_field='MATRICULA'),
        ),
    ]
