# Generated by Django 3.2.21 on 2024-07-19 00:09

from django.db import migrations, models
import imagenes.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0002_auto_20231130_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='GRUPO',
            field=models.CharField(max_length=1, validators=[imagenes.models.validate_F_D]),
        ),
    ]
