# Generated by Django 3.2.21 on 2023-11-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0002_alter_imagenes_id_arma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='IMAGEN',
            field=models.ImageField(unique=True, upload_to='images/imagenes/'),
        ),
        migrations.AlterField(
            model_name='imageneslog',
            name='imagen',
            field=models.ImageField(upload_to='respaldo/imagenes/'),
        ),
    ]
