# Generated by Django 4.2.3 on 2023-07-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0002_alter_imagenes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='IMAGEN',
            field=models.FileField(upload_to='imagenes/imagenes/'),
        ),
    ]
