# Generated by Django 3.2.21 on 2023-11-06 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0003_auto_20231106_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='IMAGEN',
            field=models.ImageField(unique=True, upload_to='images/imagenes/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
