# Generated by Django 4.2.3 on 2023-07-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0003_alter_imagenes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='ID_ALTERNA',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
