# Generated by Django 3.2.21 on 2023-11-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0004_alter_imagenes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
