# Generated by Django 4.2.3 on 2023-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0004_alter_imagenes_id_alterna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='IMAGEN',
            field=models.FileField(upload_to='static/images/imagenes'),
        ),
    ]
