# Generated by Django 4.2.3 on 2023-09-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0005_armamento_cuip_responsable'),
        ('catalogos', '0017_delete_armamento'),
        ('imagenes', '0008_alter_imagenes_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imakey', models.DecimalField(decimal_places=0, max_digits=10)),
                ('desima', models.CharField(max_length=80)),
                ('folio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('grupo', models.CharField(max_length=1)),
                ('imagen', models.FileField(upload_to='respaldo/imagenes/')),
                ('usuario', models.CharField(max_length=50)),
                ('ultima_modificacion', models.DateTimeField()),
                ('Institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.institucion')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.dependencia')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.entidad')),
                ('id_alterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagenes.imagenes')),
                ('id_arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armamento.armamento', to_field='ID_ARMA')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipo_imagen')),
            ],
        ),
    ]
