# Generated by Django 4.2.3 on 2023-09-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0009_imageneslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageneslog',
            name='estado',
            field=models.CharField(default='x', max_length=20),
        ),
    ]
