# Generated by Django 4.2.3 on 2023-09-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0011_alter_imageneslog_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageneslog',
            old_name='Institucion',
            new_name='institucion',
        ),
    ]
