# Generated by Django 4.2.3 on 2023-09-07 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0005_armamento_cuip_responsable'),
        ('imagenes', '0012_rename_institucion_imageneslog_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageneslog',
            name='dependencia',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='imageneslog',
            name='entidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='imageneslog',
            name='id_alterna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='imagenes.imagenes'),
        ),
        migrations.AlterField(
            model_name='imageneslog',
            name='id_arma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='armamento.armamento', to_field='ID_ARMA'),
        ),
        migrations.AlterField(
            model_name='imageneslog',
            name='institucion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='imageneslog',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
