# Generated by Django 4.2.3 on 2023-09-12 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0014_alter_armamentolog_id_alterna'),
        ('imagenes', '0013_alter_imageneslog_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageneslog',
            name='id_alterna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagenes.imagenes'),
        ),
        migrations.AlterField(
            model_name='imageneslog',
            name='id_arma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='armamento.armamento', to_field='ID_ARMA'),
        ),
    ]
