# Generated by Django 4.2.3 on 2023-09-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0014_alter_armamentolog_id_alterna'),
        ('catalogos', '0017_delete_armamento'),
        ('imagenes', '0014_alter_imageneslog_id_alterna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='DEPENDENCIA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.dependencia'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='ENTIDAD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.entidad'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='ID_ARMA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='armamento.armamento', to_field='ID_ARMA'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='INSTITUCION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.institucion'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='TIPO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.tipo_imagen'),
        ),
    ]
