# Generated by Django 4.2.3 on 2023-09-14 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imagenes', '0015_alter_imagenes_dependencia_alter_imagenes_entidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
