# Generated by Django 4.2.3 on 2023-09-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0016_alter_imagenes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageneslog',
            name='id_alterna',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='imageneslog',
            name='id_arma',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
