# Generated by Django 4.2.3 on 2023-09-18 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0020_alter_armamento_municipio'),
        ('imagenes', '0017_alter_imageneslog_id_alterna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='ID_ARMA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='armamento.armamento', to_field='ID_ARMA'),
        ),
    ]
