# Generated by Django 3.2.21 on 2023-10-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0018_alter_imagenes_id_arma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='IMAGEN',
            field=models.FileField(unique=True, upload_to='images/imagenes/'),
        ),
    ]
