# Generated by Django 3.2.21 on 2023-10-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0019_alter_imagenes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='ID_ARMA',
            field=models.TextField(default='x'),
        ),
    ]
