# Generated by Django 3.2.21 on 2023-10-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0020_alter_imagenes_id_arma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenes',
            old_name='ID_ARMA',
            new_name='MATRICULA',
        ),
    ]
